name: easeml
version: 0.1.4
summary: Ease.ml is a declarative machine learning service platform.
description: |
  Ease.ml is a declarative machine learning service platform. 
  It enables users to upload their datasets and start model selection and tuning jobs. 
  Given the schema of the dataset, ease.ml does an automatic search for applicable models and performs training, prediction and evaluation.
  All models are stored as Docker images which allows greater portability and reproducibility.

confinement: strict
#confinement: classic #strict
grade: devel
#grade: stable

base: core18

plugs:
  mongodb-plug:
    interface: content
    target: $SNAP_DATA/shared
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: docker-env
hooks:
  configure:
    plugs:
      - network
      - network-bind
slots:
  mongodb-slot:
    interface: content
    write:
      - $SNAP_DATA/share

parts:
  buildenv:
    plugin: dump
    source: dev/scripts/linux/docker/
    override-build: |
      ./prepare-temp-build-env-engine.sh
  easeml:
    plugin: dump
    source: .
    after: [buildenv]
    override-build: |
      echo "Exporting Paths"
      export GOROOT=$HOME/temp_install/go
      export GOPATH=$HOME/go
      export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin:$HOME/temp_install/bin:$HOME/temp_install/go/bin
      npm set unsafe-perm true
      cd engine
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      make install INSTALL_PATH=$SNAPCRAFT_PART_INSTALL/bin/
  mongod:
    source: http://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.2.0.tgz
    plugin: dump
    stage-packages:
        - libssl1.0.0
        - libasn1-8-heimdal
        - libgssapi3-heimdal
        - libhcrypto4-heimdal
        - libheimbase1-heimdal
        - libheimntlm0-heimdal
        - libhx509-5-heimdal
        - libkrb5-26-heimdal
        - libldap-2.4-2
        - libnghttp2-14
        - libroken18-heimdal
        - librtmp1
        - libsasl2-2
        - libwind0-heimdal
        - libc6
        - libcomerr2
        - libdb5.3
        - libgcc1
        - zlib1g
    filesets:
        mongo:
            - usr
            - bin
    stage:
        - $mongo
apps:
  easeml:
    command: bin/easeml
    plugs: [home,desktop,removable-media,network, network-bind, docker-executables, docker-cli]
  mongod:
    command: bin/mongod --dbpath $SNAP_COMMON/easemlmdb
    daemon: simple
    plugs: [network, network-bind]
   
