name: TestBuildPublish
on: 
    push:
      branches:
            - workflow
env:
    CI: true
jobs:
    prepare:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [12.x]

        steps:
            - name: Set up Go 1.13
              uses: actions/setup-go@v1
              with:
                go-version: 1.13
              id: go
              
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
              

            - name: Check out code into the Go module directory
              uses: actions/checkout@v2

            - name: Get dependencies (gobuffalo)
              run: |
                go get -v -u github.com/gobuffalo/packr/v2/... 
                echo ::set-output name=status::success
              continue-on-error: true
           
            - name: Export Xterm
              run: export TERM=xterm
              
            - name: Other Dependencies
              run: |
                sudo apt-get install -y mongodb-org
                sudo python3 -m pip install pipenv
                sudo npm install rimraf -g
                         
            - name: Test
              run: |
                make test
                echo ::set-output name=status::success
              continue-on-error: true

            - name: Build
              run: make build

            - name: Publish
              run: make test
      
