name: TestBuildPublish
on: 
    push:
      branches:
            - workflow
env:
    CI: true
    TERM: xterm
jobs:
    prepare:
        services:
          mongodb:
            image: mongo:3.4.23
            ports:
              - 27017:27017
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [12.x]
        steps:
            - name: Extract Info
              id: branch_info
              run: |
                echo ::set-env name=NAME::${GITHUB_REF#refs/*/}
                echo ::set-env name=BRANCH::${GITHUB_REF#refs/heads/}
                echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}
            - name: Setup Env
              shell: bash
              run: |
                echo "::set-env name=GOPATH::${{ github.workspace }}/go"
                echo "::add-path::${{ github.workspace }}/go/bin"
            - name: Set up Go 1.13
              uses: actions/setup-go@v1
              with:
                go-version: 1.13
              id: go
              
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
                always-auth: true
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                python-version: '3.x'              

            - name: Check out code into the Go module directory
              uses: actions/checkout@v2
                                    
            - name: Init 
              run: |
                make init

            - name: Test
              run: |
                make test

            - name: Build
              run: make build

            
            - name: SETUP
              if: ${{ env.BRANCH == 'workflow' }}
              run: |
                echo ::set-env name=PUBLISH::true

            
            - name: ECHO TAG
              if: ${{ env.BRANCH == 'workflow' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
              run: |
                echo "TEST"
                echo env.TAG
                echo $TAG
                echo ${{ env.TAG }}
                echo env.$PUBLISH
                echo $PUBLISH
                echo ${{ env.$PUBLISH }}

            - name: Publish
              if: ${{ env.PUBLISH == 'true' }}
              run: |
                make publish
                echo ::set-output name=status::success
              env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PIPY_TOKEN }}
                SNAP_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
              continue-on-error: true
      
