name: TestBuildPublish
on:
  push:
    branches:
      - '*'
  create:
    tags:
      - 'v*'
env:
    CI: true
    TERM: xterm
jobs:
    prepare:
        if: ${{!contains(github.event.head_commit.message, '[Bumped Version]')}}
        services:
          mongodb:
            image: mongo:3.4.23
            ports:
              - 27017:27017
        runs-on: ubuntu-latest
        container:
          image: easeml/build-environment
          options: "--user easeml"
          env:
            GOROOT: "/usr/local/go"
            GOPATH: "/home/easeml/go"
            PATH: "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/local/pyenv/bin:/home/easeml/go/bin"
            
        steps:
            - name: Extract Info
              id: branch_info
              run: |
                echo ::set-env name=NAME::${GITHUB_REF#refs/*/}
                echo ::set-env name=BRANCH::${GITHUB_REF#refs/heads/}
                echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}

            - name: Check out code into the Go module directory
              uses: actions/checkout@v2
              with:
                persist-credentials: false
                                    
            - name: Init
              run: |
                make init

            - name: Test
              run: |
                socat TCP-LISTEN:27017,fork TCP:mongodb:27017 &
                make test

            - name: Build
              run: make build
            
            - name: Version Bump and Tag for release
              if: ${{ env.BRANCH == 'workflow' && !startsWith(github.ref, 'refs/tags')&& !contains(github.event.head_commit.message, '[Bumped Version]')}}
              run: |
                make version
                VERSION=`cat VERSION`
                echo $VERSION
                echo "USING GIT"
                remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                remote_repo_trigger="https://leaguilar:${{ secrets.ACTION_PAT }}@github.com/${GITHUB_REPOSITORY}.git"
                git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
                git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
                echo "##Adding VERSION FILES"
                git add VERSION
                git add client/javascript/easemlclient/package.json
                git add client/jupyterlab/easemlclient/package.json
                git add client/python/easemlclient/easemlclient/__init__.py
                git add schema/javascript/easemlschema/package.json
                git add schema/python/easemlschema/easemlschema/__init__.py
                git add snap/snapcraft.yaml
                git add web/package.json

                echo "##COMMITING"
                git commit -m "[Bumped Version]"
                echo "##CREATING TAG"
                git tag -a v$VERSION -m "Test tag."
                #echo "##PUSHING TAG"
                #git push $remote_repo --tag
                echo "##PUSHING"
                git push $remote_repo_trigger --follow-tags
                

            # Installation Taken from https://github.com/samuelmeuli/action-snapcraft/blob/master/index.js
            - name: Publish
              if: ${{ startsWith(github.ref, 'refs/tags') }}
              run: |
                echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
                make publish
              env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
                SNAP_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
              continue-on-error: true
      
