name: TestBuildPublish
on:
  push:
    branches:
      - '*'
  create:
    tags:
      - 'v*'
env:
    CI: true
    TERM: xterm
jobs:
    prepare:
        if: ${{!contains(github.event.head_commit.message, '[Bumped Version]')}}
        services:
          mongodb:
            image: mongo:3.4.23
            ports:
              - 27017:27017
        runs-on: ubuntu-latest
        container:
          image: easeml/build-environment
          options: "--user easeml"
        steps:
            - name: Test
              run: |
                whoami
                sudo apt install -y tree
                tree
                echo $HOME
                echo $PATH
                pwd
                cd
                pwd
                echo $HOME
                echo $PATH
                tree
            - name: Extract Info
              id: branch_info
              run: |
                echo ::set-env name=NAME::${GITHUB_REF#refs/*/}
                echo ::set-env name=BRANCH::${GITHUB_REF#refs/heads/}
                echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}

            - name: Check out code into the Go module directory
              uses: actions/checkout@v2
              with:
                persist-credentials: false
                                    
            - name: Init 
              run: |
                sudo apt install make -y
                make init

            - name: Test
              run: |
                make test

            - name: Build
              run: make build
            
            - name: Version Bump and Tag for release
              if: ${{ env.BRANCH == 'workflow' && !startsWith(github.ref, 'refs/tags')&& !contains(github.event.head_commit.message, '[Bumped Version]')}}
              run: |
                make version
                VERSION=`cat VERSION`
                echo "USING GIT"
                remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                remote_repo_trigger="https://leaguilar:${{ secrets.ACTION_PAT }}@github.com/${GITHUB_REPOSITORY}.git"
                git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
                git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
                echo "##Adding VERSION FILE"
                git add VERSION
                echo "##COMMITING"
                git commit -m "[Bumped Version]"
                echo "##CREATING TAG"
                git tag -a v$VERSION -m "Test tag."
                #echo "##PUSHING TAG" 
                #git push $remote_repo --tag
                echo "##PUSHING"
                git push $remote_repo_trigger --follow-tags
                

            # Installation Taken from https://github.com/samuelmeuli/action-snapcraft/blob/master/index.js
            - name: Publish
              #if: ${{ startsWith(github.ref, 'refs/tags') }}
              run: |
                make publish
                echo ::set-output name=status::success
              env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PIPY_TOKEN }}
                SNAP_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
              continue-on-error: true
      
